version: '3.7'

services:
  nodejs:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    restart: unless-stopped
    container_name: nodejs
    stdin_open: true
    tty: true
    networks:
      - goredan-client

volumes:
  db:

networks:
  goredan-client: